php artisan make:model TaiKhoan
php artisan make:model LoaiQuat
php artisan make:model Quat
php artisan make:model ChiTietQuat
php artisan make:model NhanVien
php artisan make:model KhachHang
php artisan make:model NhaCungCap
php artisan make:model HoaDonBan
php artisan make:model ChiTietHDB
php artisan make:model HoaDonNhap
php artisan make:model ChiTietHDN
php artisan make:model ChuDe
php artisan make:model BaiViet